version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - pg-dump:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
      - POSTGRES_DATABASE=example

  email:
    image: jinkyuhan/msa-email-service
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - ./email:/email-app
      - /email-app/build
      - /email-app/bin
      - /email-app/.gradle
    depends_on:
      - db

volumes:
  pg-dump: