
@startuml
class MailAccount {
  String sf

}
class Mail {
  String id
  String title
  String content
  Mail sender
  Mail receiver
}

class MailContent {

}

class MailService {

}


  ' Mail *-- MailContent 
@enduml