server:
    tomcat:
        accesslog:
            enabled: true
            directory: '/dev'
            prefix: 'stdout'
            buffered: false
            suffix:
            file-date-format:
spring:
    resources:
      static-locations: classpath:/views/statics/
    config:
      activate:
        on-profile: dev
    devtools:
        remote:
            restart:
                enabled: true
            secret: ${SPRING_DEVTOOL_REMOTE_SECRET}
        restart:
            enabled: true
    datasource:
        platform: ${SPRING_DATASOURCE_PLATFORM}
        url: jdbc:${SPRING_DATASOURCE_PLATFORM}://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/email
        hikari:
          maximum-pool-size: 4
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                default_schema: ${SPRING_JPA_DEFAULT_SCHEMA}
        generate-ddl: true
        show-sql: true
    thymeleaf:
      prefix: classpath:views/
      check-template-location: true
      suffix: .html
      mode: HTML
      cache: false
      order: 0
