spring:
    mail:
        host: smtp.gmail.com
        username: ${GMAIL_USERNAME}
        password: ${GMAIL_PASSWORD}
        port: ${GMAIL_SMTP_PORT}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

service:
    name: example
    mail:
        senderAddress: ${SERVICE_MAIL_SENDER_ADDRESS}
        authCode:
          ttl: ${SERVICE_MAIL_AUTHCODE_TTL}
          length: ${SERVICE_MAIL_AUTHCODE_LENGTH}
    tableName:
        mail: ${TABLENAME_MAIL}
        account: ${TABLENAME_ACCOUNT}

