spring:
    mail:
        host: smtp.gmail.com
        username: ${GMAIL_USERNAME}
        password: ${GMAIL_PASSWORD}
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

service:
    name: example
    mail:
        senderAddress: gkswlsrb95@gmail.com
        authCode:
          ttl: 30
          length: 6
    tableName:
        mail: mail
        account: account

